### ISSUE TITLE
How to get `goa_human.gaf`?

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#11]
The following line appears to refer to the Gene Ontology Annotation file
https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/extracRelation.pl#L136

This file you used should be included in the repository. It should be documented how the file was acquired, and even better, the code should automatically download it to the right place if it is not there already. If it was modified after downloading, code that did the modifications should also be included in your repository and both the raw and modified versions should be included.

It may not be obvious to most readers what this file is, so it should also be better documented. The repository should clearly state which version of the GOA database was used for the analysis presented in the paper.

**Comment by huihui1126** [comment]
goa_human.gaf has been provided in /drugSim-pathway/v1.1/PathwayData/. And It was downloaded from GeneOntology via url "http://current.geneontology.org/annotations/goa_human.gaf.gz". The download time and url were updated in the annotation of extracRelation.pl
