### ISSUE TITLE
How was `combine_score.txt ` generated?

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#12]
It is not obvious from the repository how https://github.com/huihui1126/drugSim-pathway/blob/main/combine_score.txt was generated. The code that generated it should be included in the repository or if it was downloaded from an external source, it should be referenced

**Comment by huihui1126** [comment]
Combine_score.txt is a file including drug-target interaction and possibility of the interaction which includes the drug-target interactions used in our study.
Authors can replace this file by their own drug-target interaction files.
