### ISSUE TITLE
Command line arguments not documented in `PathSim.py`

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#2]
The beginning of the `PathSim.py` script extracts a variable `star` from the first system argument after the program name
https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/PathSim.py#L5-L6

but it is neither documented in the code, nor possible for the user to run `-h`/`--help` to get more information. Please use a modern CLI generator module like `click`, or less preferably, the builtin `argparse` to improve the usability of this script.

**Comment by huihui1126** [comment]
The usage for PathSim.py was updated in the head of PathSim.py. PathSim.py was called by extracRelation.pl which is the main program. So the input files of pathsim.py were produced by extracRelation.pl. And input and output files of pathsim.py were deleted as the intermediate results.
https://github.com/huihui1126/drugSim-pathway/blob/46ed3690a59dcf0fff4840967da43ec0f0316634/v1.1/extracRelation.pl#L101
