### ISSUE TITLE
Data required to run `PathSim.py` is missing

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#3]
The `PathSim.py` script references several data files that are neither included in this repository, automatically downloaded during runtime, nor documented how the user can get them. Here are the offending lines:

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/PathSim.py#L10-L14

As it is, this script is unusable so the results can neither be reproduced nor verified

**Comment by huihui1126** [comment]
extracRelation.pl is the main program of this project which call the pathsim.py inside it.
So the input files of pathsim.py were produced by extracRelation.pl. And they were deleted as the intermediate results.
https://github.com/huihui1126/drugSim-pathway/blob/080178a6801a75a4df5a382935eb9fff9043ca18/v1.1/extracRelation.pl#L101

**Comment by huihui1126** [comment]
extracRelation.pl is the main program of this project which call the pathsim.py inside it.
So the input files of pathsim.py were produced by extracRelation.pl. And they were deleted as the Intermediate results.
