### ISSUE TITLE
Results of `PathSim.py` are missing

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#4]
The `PathSim.py` script appears to generate two output files `anhai_pathsim.txt` and `result.txt`

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/PathSim.py#L79-L91

but neither of them are included in the repository nor does the repository list an alternate location where they are hosted. Please include them directly in the github repository. If they are too large for github, then they can be gzipped and stored in the repo with Git LFS. If they are still too large, then [Zenodo](https://zenodo.org/) will host up to 50GB files with no questions asked, and you can link to the record via the README.

**Comment by huihui1126** [comment]
extracRelation.pl is the main program of this project which call the pathsim.py inside it.
So the input files of pathsim.py were produced by extracRelation.pl. And input and output files of pathsim.py were deleted as the intermediate results.
https://github.com/huihui1126/drugSim-pathway/blob/080178a6801a75a4df5a382935eb9fff9043ca18/v1.1/extracRelation.pl#L101
