### ISSUE TITLE
Better file extensions

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#5]
Several files throughout the repository, including the two data files currently hosted (https://github.com/huihui1126/drugSim-pathway/blob/main/combine_score.txt and https://github.com/huihui1126/drugSim-pathway/blob/main/inflamationresponse.txt) as well as several files that appear to be generated by the scripts

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/PathSim.py#L90, https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/extracRelation.pl#L80

and others in the perl file appear to be tabular data, but use the `txt` extensions. These should be changed to `tsv` or `csv` where applicable for several reasons:

1. GitHub can pretty display content with correct file extensions
2. It helps users better understand what these files are
3. It's pedantically more correct

**Comment by huihui1126** [comment]
Thanks for your suggestion.
The input and output file of main program have change to csv extension for better reading for authors.
