### ISSUE TITLE
List perl requirements for `extracRelation.pl`

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#6]
Perl is definitely out of vogue in bioinformatics, so many people are probably not familiar with its syntax nor its usage. Like in #1, there should be a requirements list for the `extracRelation.pl`. I'm not sure what the perl equivalent of `requirements.txt` is, but at a minimum, the README should include an explanation that this is a perl script, what version of perl should be installed to run it, how to install the requirements to run it, and then how to run it.

I would also seriously advise not including perl code in modern publications and instead porting this script to Python, because it creates a challenge for many people to understand your work.

**Comment by huihui1126** [comment]
The requirements of this program have been updated in README.md.
About the perl code,  I think the conclusion of the study will not change no matter perl or python or any other programming language was used.
