### ISSUE TITLE
Missing dependent script `hclu.r`

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#7]
`extracRelation.pl` seems to make a system call to run `hclu.r`. This is not included in the repository so this script fails.

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/extracRelation.pl#L92-L93

Please include this script in the repository. Like in #1 and #6, this is yet another programming language that your README must explain how to install, what environment and requirements you used, etc..

**Comment by huihui1126** [comment]
The requirement for hclu.r was listed in the head of hclu.r and README.md.

https://github.com/huihui1126/drugSim-pathway/blob/617afba1f5bbe439aac95d834a04e0b08bb47019/v1.1/hclu.r#L1-L4
