### ISSUE TITLE
Data required to run `extracRelation.pl` are missing

### ISSUE THREAD

**Issue by cthoyt** [huihui1126/drugSim-pathway#8]
The following subroutine relies on a file called `immuneterm.txt` that is not present in the repository

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/extracRelation.pl#L126-L153

The script can still be successfully run becuase the call to this subroutine has been commented out 

https://github.com/huihui1126/drugSim-pathway/blob/6042830395bbf4dfbdea8b72dd4de11bac25e269/extracRelation.pl#L40

but this should still be fixed.

**Comment by huihui1126** [comment]
The  immuneterm.txt is a sub file only including immune related GOBP terms extracting from the GOA file.

In the new version, immuneterm.txt was not required for  extracRelation.pl, because GOA file is provided.

**Comment by huihui1126** [comment]
The  immuneterm.txt is a sub file only including immune related GOBP terms extracting from the GOA file.

In the new version, immuneterm.txt was not required for  extracRelation.pl, because GOA file is provided.
